
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: localworker-editor-role
rules:
- apiGroups:
  - worker.saved.sh
  resources:
  - localworkers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - worker.saved.sh
  resources:
  - localworkers/status
  verbs:
  - get
